version: '3'
services:
 web-mcadima:
  image: webdevops/php-apache-dev:7.3
  container_name: web-mcadima-icorrea
  restart: always
  user: application
  environment:
  - WEB_ALIAS_DOMAIN=ecomsur.develop.prueba
  - WEB_DOCUMENT_ROOT=/var/www/html
  - PHP_DATE_TIMEZONE=EST
  - PHP_DISPLAY_ERRORS=1
  - PHP_MEMORY_LIMIT=2048M
  - PHP_MAX_EXECUTION_TIME=300
  - PHP_POST_MAX_SIZE=500M
  - PHP_UPLOAD_MAX_FILESIZE=1024M
  - CONTAINER_UID=33
  volumes:
  - E:\FrontApp\magento2Demo\magentoDemo:/app:cached
  ports:
  - "32823:22"
  links:
  - mysql-mcadima
 mysql-mcadima:
  image: mariadb:10.4
  container_name: mysql-mcadima-icorrea
  restart: always
  ports:
  - "3306:3306"
  environment:
  - MYSQL_ROOT_PASSWORD=root
  - MYSQL_DATABASE=magento
  volumes:
  - db-data:/var/lib/mysql-mcadima
 phpmyadmin:
  container_name: phpmyadmin-mcadima-icorrea
  restart: always
  image: phpmyadmin/phpmyadmin:latest
  environment:
  - MYSQL_ROOT_PASSWORD=root
  - PMA_USER=root
  - PMA_PASSWORD=root
  ports:
  - "8080:80"
  links:
  - mysql-mcadima:db
  depends_on:
  - mysql-mcadima
volumes:
 db-data:
  external: false
